# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
   aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:  
      - image: amazon/aws-cli
      steps:
        - checkout # check out the code in the project directory
        - run: 
            name: Create Cloudformation Stack
            command: |
               aws cloudformation deploy \
               --template-file template.yml \
               --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
               --region us-east-1


  add_ipto_inventory:
    docker:  
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
          aws ec2 describe-instances \
        --query 'Reservations[*].Instances[*].PublicIpAddress' \
        --output text >> inventory


  configure_infrastructure:

    docker:
    - image: python:3.7-alpine3.11
    steps:
    - checkout
    - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["15:04:8a:7b:7f:d7:34:8d:bc:28:53:8d:c3:6b:69:e6"] 
    - run:
        name: Install Ansible
        command: |
           apk add --update ansible 
        # Install Ansible
    - run:
        name: Run Playbook and Configure server
        command: | 
          ansible-playbook -i inventory.txt main4.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
             requires:  
                 - create_infrastructure
       